### ISSUE TITLE
Gates on two qudits with guard levels

### ISSUE THREAD

**Issue by relugzosiraba** [LLNL/Juqbox.jl#14]
Section 6.1 of the paper (https://arxiv.org/pdf/2106.14310.pdf) gives an example for the case right below Eq. (2.16) [*]. You say in Section 6.1 that “While there are additional resonant
frequencies in the system, they are sufficiently close to the above set to trigger all
desired transitions in the system.”

1) What is the measure for “being sufficiently close”? If one of the qudits has 2 essential + 1 guard (a transmon) and the other has 8 essential + 3 guards (a cavity mode), what other frequencies would you need to include? I am assuming a gate which acts on transmon as identity and on cavity mode as non-identity affecting some or all essential levels.

2) For the case right below Eq. (2.16); n1 = 3, n2 = 3. How many essential and guard levels are considered?

[*] However, it seems that the number of guard levels is zero for the latter. Asking about this in Question 2 above.

**Comment by andersp** [comment]
For the CNOT case in Section 6.1 in the above paper there are 2 essential and 1 guard level per subsystem (as is stated in the first sentence of that section). The duration of the gate is T = 75 ns, corresponding to a frequency resolution of df = 1/T = 0.0133 GHz. Thus, differences in carrier wave frequencies that are smaller than 'df' can be ignored. Out of the 6 resonant frequencies for Omega1, only 2 are therefore significantly different: {0, -xi1}. Same argument applies to Omega2. In the paper we added a third frequency(-xi_{12}), which may not have been strictly necessary because xi_{12}/2 pi = 0.01 GHz.
Regarding your transmon/resonator case, you have to write down the frequencies that are resonant for your case. Then eliminate redundant frequencies based on your gate duration.
