### ISSUE TITLE
How to store Ipopt optimization results

### ISSUE THREAD

**Issue by relugzosiraba** [LLNL/Juqbox.jl#17]
Is there a quick way to store the terminal output?

<img width="571" alt="_Ipopt" src="https://user-images.githubusercontent.com/32973443/125487615-ba6ec1bd-e71a-432d-a67d-42df9d47ba30.png">

**Comment by fortinog** [comment]
Once you define the IPOPT problem structure, you can add an option to print the output to file. Something like 
```
# Define IPOPT problem structure
prob = Juqbox.setup_ipopt_problem(params, wa, nCoeff, minCoeff, maxCoeff, maxIter, lbfgsMax, startFromScratch)
# Ask to print convergence history to file "out.txt"
addOption(prob, "output_file", "out.txt")
```
There are other options if you're interested in a different amount of output (for instance, by using the option `file_print_level`). Other options can be found in the IPOPT documentation here: https://coin-or.github.io/Ipopt/OPTIONS.html

**Comment by relugzosiraba** [comment]
Following the link, I’ve also tried to set max wall time:

addOption(prob, "max_wall_time", 10)

But I get the error:

ERROR: LoadError: IPOPT: Couldn't set option 'max_wall_time' to value '10'.

What is the right way to do it?

**Comment by relugzosiraba** [comment]
Following the link, I’ve also tried to set max wall time (10 seconds here):

addOption(prob, "max_wall_time", 10)

But I get the error:

`ERROR: LoadError: IPOPT: Couldn't set option 'max_wall_time' to value '10'.`

What is the right way to do it?

**Comment by fortinog** [comment]
Some digging into the Ipopt.jl package seems to indicate that this is not currently supported (see the issue here: https://github.com/jump-dev/Ipopt.jl/pull/277). Currently Ipopt.jl uses version 3.13 of Ipopt by default and the `max_wall_time` option is a feature of version 3.14 which may be exposed to users in the future. The `max_cpu_time` option does work on my installation, perhaps that may be helpful until a future release of Ipopt.jl exposes `max_wall_time`.
