### ISSUE TITLE
Ignore certain initial conditions

### ISSUE THREAD

**Issue by jasonchadwick** [LLNL/Juqbox.jl#18]
By default, Juqbox will optimize for every possible initial occupation of Ne levels - is it possible to tell Juqbox to ignore some of these initial conditions if we don't care about how those states evolve? (I am looking at a gate that promotes a 2-state qubit to a 4-state ququart, so I want that oscillator to have 4 essential levels but I don't care what happens if it starts in state 2 or 3 because I expect it to always start in states 0 or 1)

**Comment by fortinog** [comment]
Due to the way Juqbox pre-allocates arrays for efficiency I don't believe it is possible to specify 4 essential energy levels without performing an optimization over all 4 initial states. This particular system is fairly small and I wouldn't expect a huge overhead in optimizing over all initial conditions, but if you really wanted to do this it may be possible to hack it by specifying the number of essential energy levels as `Ne = 2` and adding the other 2 "essential" levels in as guard levels. That is, you'd do something like 
```
Ne = 2
Ng_original = 2 # original number of guard levels desired
Ng = Ng_original + 2
```
Juqbox then would typically assume (in this case anyway) that you're tracking 6 energy levels and the 4 highest levels are guard levels. By default, Juqbox accumulates the average population in these states according to weights specified in the `wmat` field in the `params` struct. It may be possible to then zero out the weight entries for the guard levels you want to treat as essential levels by manually modifying `wmat` via something like
```
params.wmat[3,3] = 0.0
params.wmat[4,4] = 0.0
```
This way there is no penalty for using the second+third excited states so that they are basically "essential" levels, and Juqbox would then allow you to only track 2 initial states since it believes there are only 2 essential levels. I hope I understood your question correctly and this addresses what you wanted, let me know if it doesn't. This procedure may also result in some unexpected plotting (as Juqbox wasn't quite designed to be used in this manner), but a call like
```
objv, grad, unitaryhistory, fidelity = Juqbox.traceobjgrad(pcof, params, wa, true, true);
```
should provide you with the state history in the `unitaryhistory` array which you can manually plot.

**Comment by jasonchadwick** [comment]
That's what I was looking for, thanks!
