### ISSUE TITLE
Choosing D1 parameter

### ISSUE THREAD

**Issue by jasonchadwick** [LLNL/Juqbox.jl#2]
How should we choose `D1` (num of B-spline coefficients)? Should it depend on pulse duration?

**Comment by andersp** [comment]
The actual number depends on the setup. For superconducting circuits, our rule of thumb is 10-15 B-spline coefficients per 100 ns. So if the duration is T=200 ns, use D1=40-50.

**Comment by relugzosiraba** [comment]
nCoeff = 2*Nctrl*Nfreq*D1

For long gates acting on many levels, I get high fidelities by choosing Nfreq small but D1 large. However, this gives me noisy Fourier spectrums with many little peaks around the main peaks. A sample representing this for Nfreq = 2 (with main frequencies 4.1 and 4.8 GHz for transmon and cavity coupled to it) and D1 = 500:

![test-ctrl-lab-fft-log](https://user-images.githubusercontent.com/32973443/124048551-36c75e00-d9dc-11eb-8072-3c8047d3420f.png)

If I instead keep D1 small and constant but increase Nfreq (so that I would use similar number of coefficients as before), can I get rid of the little peaks? I know I would get more main peaks in that case but I want to remove the noise created by the little peaks.
