### ISSUE TITLE
p, q, evalctrl

### ISSUE THREAD

**Issue by relugzosiraba** [LLNL/Juqbox.jl#21]
Are pfunc, qfunc calculated by

`pfunc, qfunc = Juqbox.evalctrl(params, pcof, td, q)`

correspond to p, q in Eq. (4) of https://arxiv.org/pdf/2001.01013.pdf?

I am using p, q in QuTiP master equation (probably as you did in https://arxiv.org/pdf/2005.13165.pdf) but the optimal pulses giving high fidelity in Juqbox does not work (low fidelity) in QuTiP. How should the output p, q be used in QuTiP? I can share my code. Could you share your code?

**Comment by relugzosiraba** [comment]
The inaccuracy between the two packages might be due to the minus sign in Eq. (4) of https://arxiv.org/pdf/2005.13165.pdf. So, u2 = -q.

**Comment by relugzosiraba** [comment]
Even after the sign change, it seems that plugging the optimal pulse calculated from Juqbox into QuTiP's mesolve() or propagator() does not provide expected results. I attached my code that I use to run Juqbox pulses in QuTiP mesolve() or propagator(). Please let me know if something looks not correct.

[juqbox_to_qutip.zip](https://github.com/LLNL/Juqbox.jl/files/7394352/juqbox_to_qutip.zip)

**Comment by fortinog** [comment]
Hi, could you also share the Juqbox script you used to set up the optimization?

**Comment by relugzosiraba** [comment]
Here it is:

[run_script.zip](https://github.com/LLNL/Juqbox.jl/files/7406327/run_script.zip)

**Comment by fortinog** [comment]
Do you have the optimal coefficients Juqbox found saved to file as well? I'd like to run a quick experiment using those if you have that available. One thing that I did notice is that in your Juqbox script it looks like you have `useMHz = true` so that when you evaluated the control functions in time they were output in units of MHz rather than rad/ns. Given that the constant Hamiltonian terms are the same in both codes, the evolution would likely not be the same in QuTiP as the control Hamiltonian is an order of magnitude larger than the Hamiltonian Juqbox used to find the optimal coefficients.

**Comment by relugzosiraba** [comment]
The optimal coefficients: 
[optimal.zip](https://github.com/LLNL/Juqbox.jl/files/7420945/optimal.zip)


Thanks for pointing out the units. I’ll use the correct units and then will try again. Please let me know about your experiment.
